-- Таблица рейтингов MPA (создаётся первой, т.к. на неё есть внешние ключи)
CREATE TABLE IF NOT EXISTS mpa_ratings (
                                           id INTEGER PRIMARY KEY,
                                           name VARCHAR(10) NOT NULL UNIQUE
);

-- Таблица жанров
CREATE TABLE IF NOT EXISTS genres (
                                      id INTEGER PRIMARY KEY,
                                      name VARCHAR(50) NOT NULL UNIQUE
);

-- Таблица пользователей
CREATE TABLE IF NOT EXISTS users (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     email VARCHAR(255) NOT NULL UNIQUE,
                                     login VARCHAR(50) NOT NULL,
                                     name VARCHAR(255),
                                     birthday DATE NOT NULL,
                                     CONSTRAINT chk_login_no_spaces CHECK (login NOT LIKE '% %')
);

-- Таблица фильмов
CREATE TABLE IF NOT EXISTS films (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     name VARCHAR(255) NOT NULL,
                                     description VARCHAR(200),
                                     release_date DATE NOT NULL,
                                     duration INT NOT NULL,
                                     mpa_rating_id INT,
                                     FOREIGN KEY (mpa_rating_id) REFERENCES mpa_ratings(id)
);

-- Связь фильм-жанр (многие ко многим)
CREATE TABLE IF NOT EXISTS film_genres (
                                           film_id BIGINT NOT NULL,
                                           genre_id INTEGER NOT NULL,
                                           PRIMARY KEY (film_id, genre_id),
                                           FOREIGN KEY (film_id) REFERENCES films(id) ON DELETE CASCADE,
                                           FOREIGN KEY (genre_id) REFERENCES genres(id)
);

-- Таблица лайков (пользователь лайкнул фильм)
CREATE TABLE IF NOT EXISTS film_likes (
                                          film_id BIGINT NOT NULL,
                                          user_id BIGINT NOT NULL,
                                          PRIMARY KEY (film_id, user_id),
                                          FOREIGN KEY (film_id) REFERENCES films(id) ON DELETE CASCADE,
                                          FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- Таблица дружбы
CREATE TABLE IF NOT EXISTS friends (
                                           user_id BIGINT NOT NULL,
                                           friend_id BIGINT NOT NULL,
                                           status BOOLEAN NOT NULL, -- true = подтверждённая, false = неподтверждённая
                                           PRIMARY KEY (user_id, friend_id),
                                           FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
                                           FOREIGN KEY (friend_id) REFERENCES users(id) ON DELETE CASCADE
);